### ISSUE TITLE
Add commented default log level parameters to config file

### ISSUE THREAD

**Issue by bpcurse** [ma1uta/ma1sd#14]
I did not find a document explaining how to set the log level in config.
Could this be added to the documentation?

**Comment by NullIsNot0** [comment]
It's already documented in [docs/troubleshooting.md](https://github.com/ma1uta/ma1sd/blob/master/docs/troubleshooting.md).
You need to provide either `-v` (verbose)  or environment variable `MA1SD_LOG_LEVEL=debug`.

**Comment by bpcurse** [comment]
Thank you for the fast reply.

Is it possible to set `MA1SD_LOG_LEVEL=debug` in the config file, too?
If you install an ma1sd package from a repository wouldn't this be more convenient than setting an ENV or manipulating the systemd service file?

**Comment by NullIsNot0** [comment]
I think debug logging is not what you want for normal ma1sd use, that's why it shouldn't be a problem to manually run ma1sd with `-v` or env variable `MA1SD_LOG_LEVEL=debug`.
Of course, it would be a nice feature to set logging severity in config file, but it needs to be implemented by someone (who believes that this functionality is really necessary).

**Comment by bpcurse** [comment]
> I think debug logging is not what you want for normal ma1sd use

:laughing:  That is indeed not my intent, it is the opposite.
I would like to reduce verbosity from `info` to `warning` or maybe even `error` by setting parameters in the config file.

Will change the title of this issue to a feature request.

**Comment by ma1uta** [comment]
I close this issue because 2.3.0 has ability to configure log level: https://github.com/ma1uta/ma1sd/blob/master/docs/configure.md#logging
Also in the 2.4.0 you can setup log files.
